name: Build and Publish Snapshot

on:
  push:
    branches: [ develop ]

jobs:
  prepare-maven-local:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle Plugin Publish Local
        run: |
          ./gradlew :Packager:publishToMavenLocal

  build:

    needs: prepare-maven-local
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build

  publish-snapshot:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle Maven Publish
        run: |
          ./gradlew publishMavenJavaPublicationToMavenRepository
        env:
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_PWD: ${{ secrets.PGP_PWD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - name: Gradle Plugin Publish
        run: |
          ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
        env:
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_PWD: ${{ secrets.PGP_PWD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}