name: PR Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run unit tests
        run: ./gradlew Library:test
      - name: Upload Failing Unit Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Unit and Int Test Failure Results
          path: ./Library/build/reports/tests/**
